In [14]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("sample.csv")
df.head(5)

,Number,Age,Sex,Source,Diagnosis,Sleep quality,Sleep latency,Sleep time,Sleep efficiency,Sleep disorder,Hypnagogue,Daytime dyfunction
0,151001001,28,male,Outpatient,Schizophrenia,1,0,0,0,2,2,2
1,151001003,65,female,Outpatient,Schizophrenia,2,3,2,1,2,2,0
2,151001006,63,female,Outpatient,Depression,1,1,1,1,0,2,0
3,151001007,30,female,Outpatient,Depression,3,3,3,3,3,3,2
4,151001012,67,female,Outpatient,Mental disorders due to vascular disease,1,0,2,1,1,3,1

In [15]:
df.tail(5)

,Number,Age,Sex,Source,Diagnosis,Sleep quality,Sleep latency,Sleep time,Sleep efficiency,Sleep disorder,Hypnagogue,Daytime dyfunction
6344,170929113,17,female,Outpatient,"Anxiety,Sleep disorder",1,2,2,0,1,3,2
6345,170929116,49,male,Outpatient,Somatization Disorder,2,2,3,3,1,0,1
6346,170929141,68,female,Outpatient,Anxiety disorder,1,1,2,1,0,0,0
6347,170930010,41,female,Outpatient,Depression,3,2,3,3,2,3,2
6348,170930067,34,male,Outpatient,Anxiety disorder,2,2,2,0,2,0,3

In [16]:
df[3:6] # DataFrame是可以进行切片的

,Number,Age,Sex,Source,Diagnosis,Sleep quality,Sleep latency,Sleep time,Sleep efficiency,Sleep disorder,Hypnagogue,Daytime dyfunction
3,151001007,30,female,Outpatient,Depression,3,3,3,3,3,3,2
4,151001012,67,female,Outpatient,Mental disorders due to vascular disease,1,0,2,1,1,3,1
5,151001013,53,male,Outpatient,"Sleep disorder,Depression",2,3,0,3,2,0,2

In [17]:
df["Diagnosis"].value_counts() # 得出各种病症的数量

Sleep disorder                                                      1699
Depression                                                          1472
Anxiety disorder                                                     861
Anxiety                                                              402
Mixed Anxiety And Depression                                         368
Bipolar Affective Disorder                                           132
Non-Organic Insomnia                                                 106
Recurrent Depressive Disorder                                         74
Adjustment Disorder                                                   58
Anxiety,Sleep disorder                                                50
Schizophrenia                                                         46
Consultation                                                          36
Sleep disorder,Depression                                             33
Sleep disorder,Mixed Anxiety And Depression                           33
Mixed Anxiety And Depression Disorder                                 32
Non-Organic Insomnia,Anxiety disorder                                 31
Depression,Sleep disorder                                             28
Somatoform Disorders                                                  28
Emotional problem                                                     28
Obsessive-Compulsive Disorder                                         28
Sleep disorder,Anxiety                                                28
Unknown                                                               28
Mixed Anxiety And Depression,Sleep disorder                           26
Sleep disorder,Anxiety disorder                                       26
Dysthymia                                                             26
Bipolar Affective Disorder,Moderate Eepressive Episode                26
Mood Disorder                                                         21
Somatization Disorder                                                 20
Anxiety,Depression                                                    20
Postpartum Depression                                                 19
                                                                    ...
Sleep disorder,osahs                                                   1
Mixed dissociative disorder,WBC abnormalities                          1
Mild cognitive impairment,Depression                                   1
Mixed Anxiety And Depression,Postpartum Depression                     1
Bipolar Affective Disorder severe attack with psychotic symptoms       1
Anxiety disorder,Epilepsy                                              1
Hysteria,Depression                                                    1
Adjustment Disorder ,Anxiety                                           1
Hypochondriacal disorder                                               1
Somatoform Disorders,Anxiety disorder                                  1
Mental Disorders Due To Physical Diseases                              1
Injury of trigeminal nerve,Sleep disorder,Anxiety                      1
Mixed Anxiety And Depression,Hepatic dysfunction                       1
Xia Yong                                                               1
Alzheimer's Disease,Sleep disorder                                     1
Sleep disorder,Hypertension,Diabetes                                   1
Panic Attacks,Mixed Anxiety And Depression                             1
Affective Disorder                                                     1
Obsessive compulsive syndrome                                          1
Sleep disorder,Pregnancy related situation                             1
Sleep disorder,Obsessive-Compulsive Disorder                           1
Acute Stress Reaction                                                  1
Anxiety disorder,Obsessive-Compulsive Disorder                         1
Bipolar Affective Disorder,Social Phobia                               1
Mixed Anxiety And Depression,Sleep Apnea                               1
Anxiety,Sleep Apnea,Sleep disorder                                     1
Depression,Personality disorder                                        1
Bulimia nervosa                                                        1
Paranoid Schizophrenia                                                 1
Severe Depression Episode with psychotic symptoms                      1
Name: Diagnosis, Length: 289, dtype: int64

In [44]:
df["Diagnosis"].describe() # 描述这一个属性的大概统计数字

count               6348
unique               289
top       Sleep disorder
freq                1699
Name: Diagnosis, dtype: object

In [45]:
df["Age"].describe() # 描述年龄属性

count    6349.000000
mean       39.892266
std        14.451461
min        16.000000
25%        28.000000
50%        38.000000
75%        51.000000
max        87.000000
Name: Age, dtype: float64